# Generated by Django 5.2.11 on 2026-02-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
