# Generated by Django 5.2.11 on 2026-02-07 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_character_scenery'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='style_guide',
            field=models.TextField(blank=True, help_text='Instrucciones de estilo visual constantes'),
        ),
        migrations.AddField(
            model_name='project',
            name='world_bible',
            field=models.TextField(blank=True, help_text='Información global (nombres, estilos, localización, etc.)'),
        ),
        migrations.AddField(
            model_name='scenery',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('note_type', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
            ],
        ),
    ]
