# Generated by Django 5.2.11 on 2026-02-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_character_metadata_project_style_guide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='merged_image_url',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='projectnote',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='projectnote',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='scenery',
            name='image_url',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='projects/characters/'),
        ),
        migrations.AddField(
            model_name='page',
            name='merged_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='projects/merged/'),
        ),
        migrations.AddField(
            model_name='panel',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='projects/panels/'),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='projects/notes/'),
        ),
        migrations.AddField(
            model_name='scenery',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='projects/sceneries/'),
        ),
    ]
