# Generated by Django 5.2.11 on 2026-02-08 00:21

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_character_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=apps.projects.models.character_upload_path),
        ),
        migrations.AlterField(
            model_name='page',
            name='merged_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=apps.projects.models.page_upload_path),
        ),
        migrations.AlterField(
            model_name='panel',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=apps.projects.models.panel_upload_path),
        ),
        migrations.AlterField(
            model_name='projectnote',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=apps.projects.models.note_upload_path),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=apps.projects.models.scenery_upload_path),
        ),
    ]
