# Generated by Django 5.2.11 on 2026-02-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_layout_style_project_max_pages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="layout_style",
        ),
        migrations.RemoveField(
            model_name="project",
            name="max_pages",
        ),
        migrations.RemoveField(
            model_name="project",
            name="max_panels",
        )
    ]
