# Generated by Django 5.2.11 on 2026-02-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0011_remove_project_layout_style_remove_project_max_pages_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="layout_style",
            field=models.CharField(default="dynamic", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="max_pages",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="project",
            name="max_panels",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
