# Generated by Django 5.2.11 on 2026-02-13 05:27

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_project_layout_style_project_max_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="panel_style",
            field=models.TextField(
                blank=True,
                help_text="Override style for this specific panel",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="panel",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to=apps.projects.models.panel_upload_path,
            ),
        ),
    ]
