# Generated by Django 5.2.11 on 2026-02-13 07:51

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_panel_panel_style_panel_reference_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=apps.projects.models.character_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="merged_image",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=apps.projects.models.page_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=apps.projects.models.panel_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=apps.projects.models.panel_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
        migrations.AlterField(
            model_name="scenery",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=apps.projects.models.scenery_upload_path,
            ),
        ),
    ]
