# Generated by Django 5.2.11 on 2026-02-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_character_image_alter_page_merged_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="world_model_summary",
            field=models.TextField(
                blank=True,
                help_text="Resumen generado por el Agente sobre las reglas del mundo",
                null=True,
            ),
        ),
    ]
